### ISSUE TITLE
Deconvolution: Visium IF data

### ISSUE THREAD

**Issue by lcolladotor** [LieberInstitute/spatialDLPFC#128]
Once we have selected the deconvolution marker genes from #127, at _broad cell type_ and _layer level_ resolutions run:

- [x] Tangram (Related to #96)
- [x] cell2location (Related to #97)
- [x] SPOTlight (Related to #89)

So in the end we'll have 6 sets of results. This will feed into #99.
